// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_appsync_graphqlEndpoint": "https://bfcxf2fr5bgzhoy3gviotljdpq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-g54e4adzsjezhmt3kgx4ylxk2e",

    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:76c25d29-c711-4548-98c1-c168faa890ff",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BfCOXB7tr",
    "aws_user_pools_web_client_id": "7d8m9a4koeqv1shkpro8f5lqif"
};

export default awsmobile;

// "aws_appsync_authenticationType": "API_KEY",
// "aws_appsync_apiKey": "da2-g54e4adzsjezhmt3kgx4ylxk2e",